---
- hosts: node
  become: yes
  tasks:
  - name: installing tomcat7
    package:
      name: tomcat7
      update_cache: yes
      state: present 
    notify:
      - restart tomcat7  
  - name: coping tomcat files
    copy:
      src: tomcat7
      dest: /etc/default/tomcat7
    notify:
      - restart tomcat7   
  - name: installing additional packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - tomcat7-docs
      - tomcat7-admin
      - tomcat7-examples
      - default-jdk 
      - ant
      - git 
    notify:
      - restart tomcat7     
  - name: copying tomcat user xml files
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat7/tomcat-users.xml
  handlers:
    - name: restart tomcat7 
      service:
        name: tomcat7 
        state: restarted